### ISSUE TITLE
DB Home system failed

### ISSUE THREAD

**Issue by mushtaqahmedmohammed** [oracle-quickstart/oci-arch-db-migration#18] opened 2021-12-20 14:53 UTC
Hi,
  like to update you, sucessfully created ExaCS VCN + Exainfra + ExaVM's by using oci-arch-ee-exa-db-mig terraform script. But DB system failed with below error: 

please advice.

oci_database_cloud_vm_cluster.exacs_vm_cluster: Still creating... [4h33m21s elapsed]
oci_database_cloud_vm_cluster.exacs_vm_cluster: Creation complete after 4h33m24s [id=ocid1.cloudvmcluster.oc1.phx.anyhqljsagwiusqaieatuqpuza4vdxl35y4vcbl7sf3nox7lbwxpcvaje3qq]
data.oci_database_db_homes.exacs_db_homes: Reading...
data.oci_database_cloud_vm_cluster.exacs_vm_cluster: Reading...
data.oci_database_db_homes.exacs_db_homes: Read complete after 0s [id=DatabaseDbHomesDataSource-1220129088]
data.oci_database_databases.exacs_databases: Reading...
data.oci_database_cloud_vm_cluster.exacs_vm_cluster: Read complete after 1s [id=ocid1.cloudvmcluster.oc1.phx.anyhqljsagwiusqaieatuqpuza4vdxl35y4vcbl7sf3nox7lbwxpcvaje3qq]

Error: Invalid index

  on database.tf line 42, in resource "oci_database_database" "exacs_starter_database":
  42:   db_home_id = data.oci_database_db_homes.exacs_db_homes.db_homes[0].id
    |----------------
    | data.oci_database_db_homes.exacs_db_homes.db_homes is empty list of object

The given key does not identify an element in this collection value.

Error: Invalid index

  on datasources.tf line 77, in data "oci_database_databases" "exacs_databases":
  77:   db_home_id     = data.oci_database_db_homes.exacs_db_homes.db_homes[0].id
    |----------------
    | data.oci_database_db_homes.exacs_db_homes.db_homes is empty list of object

The given key does not identify an element in this collection value.

bash-5.0 /projects/oci-db-migration/oci-arch-ee-exa-db-mig $ 
bash-5.0 /projects/oci-db-migration/oci-arch-ee-exa-db-mig $
![image](https://user-images.githubusercontent.com/83082336/146786345-bbb16a7e-0325-4768-8f2a-f8f97ec38ad8.png)

**Comment by mushtaqahmedmohammed** [comment] 2021-12-20 14:56
[

**Comment by mushtaqahmedmohammed** [comment] 2021-12-20 14:57
below is datasource.tf file 


## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

# Get list of availability domains
data "oci_identity_availability_domains" "ADs" {
  compartment_id = var.tenancy_ocid
}

data "oci_identity_region_subscriptions" "home_region_subscriptions" {
  tenancy_id = var.tenancy_ocid

  filter {
    name   = "is_home_region"
    values = [true]
  }
}

data "template_file" "key_script" {
  template = file("./scripts/sshkey.tpl")
  vars = {
    ssh_public_key = tls_private_key.public_private_key_pair.public_key_openssh
  }
}

data "template_cloudinit_config" "cloud_init" {
  gzip          = true
  base64_encode = true

  part {
    filename     = "ainit.sh"
    content_type = "text/x-shellscript"
    content      = data.template_file.key_script.rendered
  }
}

# Get the latest Oracle Linux image
data "oci_core_images" "InstanceImageOCID" {
  compartment_id           = var.compartment_ocid
  operating_system         = var.instance_os
  operating_system_version = var.linux_os_version
  shape                    = var.instance_shape

  filter {
    name   = "display_name"
    values = ["^.*Oracle[^G]*$"]
    regex  = true
  }
}

data "oci_database_gi_versions" "gi_version" {
  compartment_id = var.compartment_ocid
  shape          = var.exacs_infra_shape
}

data "oci_database_db_versions" "exacs_db_versions" {
  compartment_id  = var.compartment_ocid
  db_system_shape = var.exacs_infra_shape
}

data "oci_database_cloud_exadata_infrastructure" "exacs_infrastructure" {
  cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.exacs_infra.id
}

data "oci_database_cloud_vm_cluster" "exacs_vm_cluster" {
  cloud_vm_cluster_id = oci_database_cloud_vm_cluster.exacs_vm_cluster.id
}


data "oci_database_db_homes" "exacs_db_homes" {
  depends_on     = [oci_database_cloud_vm_cluster.exacs_vm_cluster]
  compartment_id = var.compartment_ocid
  vm_cluster_id  = oci_database_cloud_vm_cluster.exacs_vm_cluster.id
}

data "oci_database_databases" "exacs_databases" {
  compartment_id = var.compartment_ocid
  db_home_id     = data.oci_database_db_homes.exacs_db_homes.db_homes[0].id
}

**Comment by lfeldman** [comment] 2021-12-20 16:24
@mushtaqahmedmohammed let's analyze that. I am not able to reproduce this error, but I have been notified by some colleagues about it.

**Comment by mushtaqahmedmohammed** [comment] 2021-12-20 16:48
sure! ty! will connect on inivite you have send.

**Comment by lfeldman** [comment] 2021-12-22 17:00
@mushtaqahmedmohammed I was able to reproduce your problem. After the successful creation of `oci_database_cloud_vm_cluster.exacs_vm_cluster` resource the data source `data.oci_database_db_homes.exacs_db_homes` is empty. That is why `oci_database_database.exacs_starter_database` was failing. I have waited 5-10 minutes or so and then data source has been magically populated. It looks like a bug of RestAPIs. I mean something is still executing under the hood even though VM Cluster has been acknowledged as ready. Therefore could you please re-run terraform apply command again and re-try the apply for database resource?

**Comment by mushtaqahmedmohammed** [comment] 2021-12-22 17:50
Thanks @lfeldman for connecting!! Successfully able to create DB on ExaCS vm's with backup of it. As said, the code oci_database_database.exacs_starter_database  was failing right after creating ExaCS VM's. 
Is there something from the ExaCS Product Mangement team able to fix this kind of Bug of RestAPIs so that everything can be provisioned at one shot???

Thanks again for your help!!

**Comment by lfeldman** [comment] 2021-12-23 10:25
In the case of database provisioning with Terraform, I have noticed two behaviors that should be investigated: (1) terraform hangs in the infinite loop while the database is in fact ready and successfully backed up. In the alternative scenario, I could notice terraform apply failure, as database resource is not in the AVAILABLE state (in the middle of the BACKUP state). Let me check it internally.

**Comment by lfeldman** [comment] 2022-02-22 10:29
@mushtaqahmedmohammed I have fixed the code in an associated PR and this PR is now merged into the master branch.

**Closed** 2022-02-22 10:30 UTC
Labels: bug
